# -*- coding: utf-8 -*-
"""Classification Metrics(accuracy, precision, recall, f-1 score).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Tii5xPuQB28qovfGb5KBRTotkwFxWrs4
"""

#---------In this example we will give the model prediction AND use the matrix to find out how many correct answers our model has given!


from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
#sklearn.metrics:- compare your model result AND actual result score - It's all thinks work directly python package
#accuracy_score, precision_score, recall_score, f1_score :- It's all are Function...



#I'm provide TRUE answer (what actully happened)
y_true = [1, 0, 1, 1, 0, 1, 0]      #y_true :- my model input value

#Model's prediction is here (What it happened)
y_predi = [1, 0, 1, 0, 0, 1, 1]     #y_predi :- my model generaated output

print("Accuracy : ", accuracy_score(y_true, y_predi))
print("Precision score : ", precision_score(y_true, y_predi))
print("Recall : ", recall_score(y_true, y_predi))
print("F1 score : ", f1_score(y_true, y_predi))